### ISSUE TITLE
Unable to compile FFMPEG

### ISSUE THREAD

**Issue by tgabi333** [atyenoria/janus-webrtc-gateway-docker#1]
With a new build ffmpeg build fails:
```
Found no assembler
Minimum version is nasm-2.13
If you really want to compile without asm, configure with --disable-asm.
```

**Comment by atyenoria** [comment]
@tgabi333 
Thank you for feedback.
I fixed it in https://github.com/atyenoria/janus-webrtc-gateway-docker/commit/39fc68f5a8c4c61fa4ba1a179b4ae6b730dfdbb1

**Comment by tgabi333** [comment]
Thank you @atyenoria
