### ISSUE TITLE
One way broadcast webrtc to rtmp

### ISSUE THREAD

**Issue by blackbusters** [atyenoria/janus-webrtc-gateway-docker#11]
Hello,

First of all, sorry about this noob question, but i'm very beginner in webrtc streaming..

I want to forward webrtc stream to rtmp (I've used nginx rtmp to stream before and know a little about how to configure it). I've tried the janus server and succeeded in running the video room test demo. What i don't understand is, how to do next from this? On readme you wrote about : 
```
IP=0.0.0.0
PORT=8888
SDP_FILE=sdp.file
/root/bin/ffmpeg -analyzeduration 300M -probesize 300M -protocol_whitelist file,udp,rtp  -i $SDP_FILE  -c:v copy -c:a aac -ar 16k -ac 1 -preset ultrafast -tune zerolatency  -f flv rtmp://$IP:$PORT/rtmp_relay/atyenoria

```
But i don't know what to do with that configuration... and where should I learn about making SDP file?

Hope you can help me,

Thank you..

**Comment by atyenoria** [comment]
For general understanding, https://webrtchacks.com/sdp-anatomy/ is useful.

In order to get the SDP, you have two options.
1. get it from Chrome Debug Console when creating session
2. Janus Admin Panel. You can set this by Janus Docs

**Comment by blackbusters** [comment]
Thanks for the information. I finally managed to forward stream to rtmp by using simple SDP file posted by other user.

**Comment by HeriBrito** [comment]
Hi @blackbusters,

may you can share that SDP file, or show me where can i find it?. Thank you very much.

Regards

**Comment by blackbusters** [comment]
Hi, i use sdp posted in this link :
[https://github.com/atyenoria/janus-webrtc-gateway-docker/issues/2](2)

**Comment by HeriBrito** [comment]
Hi @blackbusters,

thank you very much !! :)
