### ISSUE TITLE
Automatically inject nginx conf file

### ISSUE THREAD

**Issue by giorgioma** [atyenoria/janus-webrtc-gateway-docker#12]
Thanks for this fantastic repo.
I am using it as my dev box for a project so I changed some configuration around for my purpose and I am automatically injecting the nginx.conf file you provided in the repo as:

```
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /usr/local/nginx/server.key -out /usr/local/nginx/server.crt \
    -subj "/C=IT/ST=Milan/L=Milan/O=Giorgio/OU=GiorgioDev/CN=example.com"

COPY nginx.conf /usr/local/nginx/host.conf

RUN sed -i.bak '/[[:space:]].#gzip/ a include host.conf;' /usr/local/nginx/nginx.conf
 ```

I am not familiar with boringssl so I used openssl, but I thought you might find this usefull as well.
**I did not submit a PR from my fork** because I changed the ./configure parameters and the nginx conf file to match my needs.

**Comment by atyenoria** [comment]
Thanks for reporting this. It looks good. I will consider it.
At now, this docker file needs some setting till trying the janus demo.
So,  I have the plans to cut down the setting task like that way.

**Comment by saroar** [comment]
@giorgioma i use ur link https://github.com/giorgioma/janus-webrtc-gateway-docker but still cant run app http://prntscr.com/li3rwm
what i am doing wrong please help me little bit thanks

**Comment by giorgioma** [comment]
@saroar I was actually using my repository just for some internal development / tests, my best guess would be to have a look at the docker build output and/or logs and see what is actually failing.

**Comment by saroar** [comment]
@giorgioma thanks i dont have luck to use this docker anyway thanks
