### ISSUE TITLE
How I can run his docker app ?

### ISSUE THREAD

**Issue by saroar** [atyenoria/janus-webrtc-gateway-docker#17]
```alif@WebRtcMediaServer:~/janus-webrtc-gateway-docker$ sudo docker run --rm --net=host --name=janus -it -P -p 80:80 -p 443:443 -p 8088:8088 -p 8004:8004/udp -p 8004:8004 -p 8089:8089 -p 8188:8188 -t atyenoria/janus-gateway-docker /bin/bash
WARNING: Published ports are discarded when using host network mode
root@WebRtcMediaServer:/# exit
exit
alif@WebRtcMediaServer:~/janus-webrtc-gateway-docker$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
alif@WebRtcMediaServer:~/janus-webrtc-gateway-docker$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
alif@WebRtcMediaServer:~/janus-webrtc-gateway-docker$ 
```

**Comment by atyenoria** [comment]
see https://github.com/atyenoria/janus-webrtc-gateway-docker#setup

**Comment by saroar** [comment]
sorry does not work i try 
you have problem with ur docker images

**Comment by saroar** [comment]
did you try your self before 
`docker run -d --name=janus -it -p 80:80 -p 443:443 -p 8088:8088 -p 8004:8004/udp -p 8004:8004 -p 8089:8089 -p 8188:8188 atyenoria/janus-gateway-docker` i try also this way but no result

**Comment by saroar** [comment]
ask help to docker slack they told me you have problem in ur docker images
would you like to please check

**Comment by saroar** [comment]
i like to know why you run `--rm` and `/bin/bash` how do you run this app with /bin/bash and --rm
docker run --rm --net=host --name="janus" -it -t atyenoria/janus-gateway-docker /bin/bash

**Comment by atyenoria** [comment]
Sorry, I've not prepared starting the janus itself. this is the todo list.
So, you should try janus by yourself after entering the docker container by /bin/bash

**Comment by saroar** [comment]
i am so sorry i am very beginner that why so can you guide me little bit how i can do it thanks advance

**Comment by saroar** [comment]
may be you can add some of this lines 

https://github.com/linagora/docker-janus-gateway/blob/master/Dockerfile

**Comment by saroar** [comment]
```RUN cp -rp ~/janus-gateway/certs /opt/janus/share/janus

COPY conf/*.cfg /opt/janus/etc/janus/

RUN apt-get install nginx -y
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 7088 8088 8188 8089
EXPOSE 10000-10200/udp

CMD service nginx restart && /opt/janus/bin/janus --nat-1-1=${DOCKER_IP}

**Comment by saroar** [comment]
so can i copy same code and past it into your docker file is it will work?

**Comment by atyenoria** [comment]
maybe work. but a little task is needed for seeing the janus official demo like video room

**Comment by saroar** [comment]
i use other docker images i share with you that is work fine but video quality was poor so i decide try yours

**Comment by saroar** [comment]
i got this error 
```Step 32/38 : RUN cp -rp ~/janus-gateway/certs /opt/janus/share/janus
 ---> Running in 91f78a665ea5
cp: cannot stat '/root/janus-gateway/certs': No such file or directory```

**Comment by hnam2812** [comment]
@saroar Did you resolve this?

**Comment by saroar** [comment]
@hnam2812 sorry i dont remember now my project doesn't have this feature
