### ISSUE TITLE
Add products into you compare performance chart

### ISSUE THREAD

**Issue by kksudo** [atyenoria/janus-webrtc-gateway-docker#22]
Can are you add to [test chart](https://raw.githubusercontent.com/atyenoria/janus-webrtc-gateway-docker/master/load-test.png) (for compare) few products :

- [flashphoner](https://flashphoner.com/)
- [flussonic](https://erlyvideo.ru/)
- [wowza](https://www.wowza.com/low-latency/webrtc-streaming-software)

**Comment by atyenoria** [comment]
Hi, Thanks for creating the issue. Why do you need the test chart for these middleware. I am not sure of why you chose.

**Comment by atyenoria** [comment]
And, what comparison test is needed for you and why?
