### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by nielsswinkels** [atyenoria/janus-webrtc-gateway-docker#23]
Sorry if this is a stupid question, but how do I run this?

I have cloned the repo, and ran
`docker build --no-cache -t atyenoria/janus-gateway-docker .`
This worked. (It took a long time)

Next I try to follow the instructions and run these commands:
```
docker run --rm --net=host --name="janus" -it -t atyenoria/janus-gateway-docker /bin/bash
docker exec -it /bin/bash janus
```
But doesn't that 2nd command do the exact same thing as the first?

```
IP=0.0.0.0
PORT=8888
/root/bin/ffmpeg -y -i  "rtmp://$IP:80/rtmp_relay/$1  live=1"  -c:v libx264 -profile:v main -s 640x480  -an -preset ultrafast  -tune zerolatency -f rtp  rtp://$IP:$PORT
```
And here it does not find `/bin/ffmpeg`?
What should IP be? The ip address of the server this is running on?

**Comment by atyenoria** [comment]
Hi @nielsswinkels . I created the script
just run
1. make build
2. make run
