### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by feixiao** [atyenoria/janus-webrtc-gateway-docker#24]
make run in OSX, but service is unreachable.

like this

➜  ~ telnet localhost 8088
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
telnet: connect to address ::1: Connection refused
telnet: Unable to connect to remote host

**Comment by atyenoria** [comment]
Can you try the vps by using docker machine?

**Comment by kuzm1ch** [comment]
I have the same  locally:
```
$ telnet localhost 8080
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```
But seems like this is normal Janus behavior ( to do not respond on this request). 
Try check availability of Janus HTTP API  using curl to location /janus/info:
```
curl localhost:8088/janus/info 
```
