### ISSUE TITLE
Can not make build on Macosx Mojave and Docker 2.0.0.3

### ISSUE THREAD

**Issue by bookmebus** [atyenoria/janus-webrtc-gateway-docker#27]
I tried ( both sudo and non sudo ) to build the on my mac I've got back this error:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I am using Docker desktop 2.0.0.3. 
Any idea?

**Comment by atyenoria** [comment]
you should run docker properly

**Comment by bookmebus** [comment]
@atyenoria Thanks. After inspection Docker.app, Macosx does not enable Daemon by default. This feature listed as experimental in the preferences. After enabling the script compile just fine.
