### ISSUE TITLE
Problem creating a Docker container using the provided Docker file

### ISSUE THREAD

**Issue by mjk6035** [atyenoria/janus-webrtc-gateway-docker#29]
Sir

I tried to create the Janus  container using Docker on a Ubuntu 18.0.4 virtual machine running on Virtual Box on a Windows 10 host.

The installation kept on failing at the following command

RUN apt-get remove -y libnice-dev libnice10 && \
    echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get   update && \
    apt-get  install -y gtk-doc-tools libgnutls28-dev -t jessie-backports  && \
    apt-get  install -y libglib2.0-0 -t jessie-backports && \
    git clone https://gitlab.freedesktop.org/libnice/libnice.git && \
    cd libnice && \
    git checkout 67807a17ce983a860804d7732aaf7d2fb56150ba && \
    bash autogen.sh && \
    ./configure --prefix=/usr && \
    make && \
    make install 

The statement succeeded after using the command listed below. The changed portions are marked with bold text

RUN apt-get remove -y libnice-dev libnice10 && \
    echo "deb **[trusted=yes]** http://**archive**.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get **-o Acquire::Check-Valid-Until=false**  update && \
    apt-get  install -y gtk-doc-tools libgnutls28-dev -t jessie-backports  && \
    apt-get  install -y libglib2.0-0 -t jessie-backports && \
    git clone https://gitlab.freedesktop.org/libnice/libnice.git && \
    cd libnice && \
    git checkout 67807a17ce983a860804d7732aaf7d2fb56150ba && \
    bash autogen.sh && \
    ./configure --prefix=/usr && \
    make && \
    make install 

After that the execution failed at the line

COPY nginx.conf /usr/local/nginx/nginx.conf

I commented the line and the installation completed successfully
Please find attached the updated docker file 
Thanks and regards
Mathew
[Dockerfiles.zip](https://github.com/atyenoria/janus-webrtc-gateway-docker/files/3028427/Dockerfiles.zip)

**Comment by atyenoria** [comment]
solved by this
https://github.com/atyenoria/janus-webrtc-gateway-docker/pull/31
