### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by mswubz** [atyenoria/janus-webrtc-gateway-docker#30]
When running make build, the following shows up:

`W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found`

**Comment by nullarch** [comment]
I have same error , did you solve this problem ?

**Comment by mjk6035** [comment]
I had a similar problem. I made a few changes to the docker file. Please check the link below for the updated docker file

https://github.com/atyenoria/janus-webrtc-gateway-docker/issues/29

**Comment by mswubz** [comment]
@mjk6035 Thank you so much, this solved my issue.

**Comment by mjk6035** [comment]
Welcome
