### ISSUE TITLE
is the sourceforge server is down ? 

### ISSUE THREAD

**Issue by nullarch** [atyenoria/janus-webrtc-gateway-docker#32]
I use dockerfile well until 3 days ago 
but I have connection error from yesterday to now.

converted 'http://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz' (ANSI_X3.4-1968) -> 'http://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz' (UTF-8)
--2019-05-02 08:51:22--  http://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... 

failed: Connection refused.

**Comment by kciter** [comment]
@Slzeroth
https://tspace.tistory.com/133

**Comment by nullarch** [comment]
@kciter  thank you ^^
