### ISSUE TITLE
build failed - Failed to fetch

### ISSUE THREAD

**Issue by arkadiopl** [atyenoria/janus-webrtc-gateway-docker#33]
I tried docker build and got this:

Sending build context to Docker daemon  31.74kB
Step 1/34 : FROM buildpack-deps:jessie
 ---> e20c27d31347
Step 2/34 : RUN sed -i 's/archive.ubuntu.com/mirror.aarnet.edu.au\/pub\/ubuntu\/archive/g' /etc/apt/sources.list
 ---> Using cache
 ---> d2c2fe6f3932
Step 3/34 : RUN rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 6f08c29d6029
Step 4/34 : RUN apt-get -y update && apt-get install -y libmicrohttpd-dev     libjansson-dev     libnice-dev     libssl-dev     libsrtp-dev     libsofia-sip-ua-dev     libglib2.0-dev     libopus-dev     libogg-dev     libini-config-dev     libcollection-dev     libconfig-dev     pkg-config     gengetopt     libtool     automake     build-essential     subversion     git     cmake     unzip     zip     lsof wget vim sudo rsync cron mysql-client openssh-server supervisor locate
 ---> Running in 18c3dd4ebea8
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [841 kB]
Get:6 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 5s (1721 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Additional information**
docker version:
Client:
 Version:           18.09.5-ce
 API version:       1.39
 Go version:        go1.12.3
 Git commit:        e8ff056dbc
 Built:             Fri Apr 12 08:22:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.3
  Git commit:       e8ff056dbc
  Built:            Fri Apr 12 08:21:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by riemers** [comment]
You do need internet for this to work. Ran the make build which also does all the image stuff and i got past that point. So might be on your side..
