### ISSUE TITLE
Projects using your solution

### ISSUE THREAD

**Issue by NeiRoSt** [atyenoria/janus-webrtc-gateway-docker#37]
Greetings!

Our team is developing a streaming dating service. In the development of the stream, we want to use your solution. I would like to know if this solution is used now for any major projects. And how stable is it? Our load requirements:
- 360p - 720p
- no more than 2000 streams with no more than 1000 viewers
- delay 3-5 sec

**Comment by atyenoria** [comment]
I don't know. what do you mean by "your solution"?

**Comment by NeiRoSt** [comment]
Sorry for my English. More precisely, I mean "your repository". We want to develop a video stream using janus+nginx+lua plugin and etc. But we are not sure whether the stream will work stably with the above requirements. Perhaps janus-webrtc-gateway-docker is used somewhere with similar requirements. Thank you.

**Comment by atyenoria** [comment]
I think that it is possible with CMAF(hls or dash) by transcoding. 
The parameters like the numbers of viewers and delay depends on  your server spec(ffmpeg gpu) and the ways of CDN. The stability depends on your skills of handling the streams in your backend language in C, Golang, Node.js..etc
