### ISSUE TITLE
how do I reach the sample page?

### ISSUE THREAD

**Issue by webfischi** [atyenoria/janus-webrtc-gateway-docker#39]
Something is very broken with janus, every single docker installation on the web shows the following error message when I try to connect with localhost:8088/janus. Am I doing sth wrong?

> [ERR] [transports/janus_http.c:janus_http_handler:1316] Invalid session (null)
[ERR] [transports/janus_http.c:janus_http_handler:1225] Invalid url /favicon.ico

Could someone please fix this issue and also add https support.

**Comment by atyenoria** [comment]
actually, that seems to be fine. you should use the janus sample html

**Comment by webfischi** [comment]
How do i use the janus sample page correctly? By now, I know that localhost ist wrong, but all answers are just leading to this page https://janus.conf.meetecho.com/docs/deploy
In the "How to use" section it only says clone, make build, make run but no word on how to connect to the sample page. With 127.0.0.1:8188 I get an error 403

**Comment by ajnozari** [comment]
@webfischi I think what @atyenoria meant was if you look on the janus GitHub you'll see an HTML folder. Take that folder and edit the JS inside of it to reflect your appropriate server destination, port, and make sure it's /janus or /janus-ws if using wss.

Then upload the files to /demo on your web server and you'll be able to load the test files.

Just make sure the server is set properly, you can see an example in each JS file.
