### ISSUE TITLE
Make Build Connection Timeout

### ISSUE THREAD

**Issue by samcrane8** [atyenoria/janus-webrtc-gateway-docker#40]
I ran make build and I get this error:

`
INSTALL	libavutil/twofish.h
INSTALL	libavutil/version.h
INSTALL	libavutil/xtea.h
INSTALL	libavutil/tea.h
INSTALL	libavutil/lzo.h
INSTALL	libavutil/avconfig.h
INSTALL	libavutil/ffversion.h
INSTALL	libavutil/libavutil.pc
Removing intermediate container 4f3d9034af2f
 ---> 15fe522a64e7
Step 15/33 : RUN ZLIB="zlib-1.2.11" && vNGRTMP="v1.1.11" && PCRE="8.41" && nginx_build=/root/nginx && mkdir $nginx_build &&     cd $nginx_build &&     wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$PCRE.tar.gz &&     tar -zxf pcre-$PCRE.tar.gz &&     cd pcre-$PCRE &&     ./configure && make && make install &&     cd $nginx_build &&     wget http://zlib.net/$ZLIB.tar.gz &&     tar -zxf $ZLIB.tar.gz &&     cd $ZLIB &&     ./configure && make &&  make install &&     cd $nginx_build &&     wget https://github.com/arut/nginx-rtmp-module/archive/$vNGRTMP.tar.gz &&     tar zxf $vNGRTMP.tar.gz && mv nginx-rtmp-module-* nginx-rtmp-module
 ---> Running in 7e08772a0de5
converted 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz' (ANSI_X3.4-1968) -> 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz' (UTF-8)
--2019-10-03 19:57:04--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
           => 'pcre-8.41.tar.gz'
Resolving ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)... 131.111.8.115
Connecting to ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)|131.111.8.115|:21... failed: Connection timed out.
Retrying.

--2019-10-03 19:59:15--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
  (try: 2) => 'pcre-8.41.tar.gz'
Connecting to ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)|131.111.8.115|:21... failed: Connection timed out.
Retrying.

--2019-10-03 20:01:27--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
  (try: 3) => 'pcre-8.41.tar.gz'
Connecting to ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)|131.111.8.115|:21... failed: Connection timed out.

`

**Comment by ghost** [comment]
I get the same :(

**Comment by Stayer** [comment]
https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz change link to this

**Comment by prasadvittaldev** [comment]
Step 15/51 : RUN ZLIB="zlib-1.2.11" && vNGRTMP="v1.1.11" && PCRE="8.41" && nginx_build=/root/nginx && mkdir $nginx_build &&     cd $nginx_build &&     wget https://ftp          .pcre.org/pub/pcre/pcre-$PCRE.tar.gz &&     tar -zxf pcre-$PCRE.tar.gz &&     cd pcre-$PCRE &&     ./configure && make && make install &&     cd $nginx_build &&     wg          et http://zlib.net/$ZLIB.tar.gz &&     tar -zxf $ZLIB.tar.gz &&     cd $ZLIB &&     ./configure && make &&  make install &&     cd $nginx_build &&     wget https://git          hub.com/arut/nginx-rtmp-module/archive/$vNGRTMP.tar.gz &&     tar zxf $vNGRTMP.tar.gz && mv nginx-rtmp-module-* nginx-rtmp-module
 ---> Running in 43a261d11a56
--2022-05-12 14:13:54--  https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz
Resolving ftp.pcre.org (ftp.pcre.org)... failed: Name or service not known.
wget: unable to resolve host address 'ftp.pcre.org'
