### ISSUE TITLE
Port 80 Conflict

### ISSUE THREAD

**Issue by ahmemx** [atyenoria/janus-webrtc-gateway-docker#42]
Hi,

Have compiled successfully, but when I run "make run" I get

nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
Makefile:13: recipe for target 'run' failed
make: *** [run] Error 1

What do I need to change?

Thanks.

**Comment by atyenoria** [comment]
Thanks for reporting the issue, but I think that you are using port 80 in host or other container. Please check it at first
