### ISSUE TITLE
boringssl issue

### ISSUE THREAD

**Issue by chi-chung-ko** [atyenoria/janus-webrtc-gateway-docker#43]
hello, i have below error when doing make build as below 
thanks.

Cloning into 'boringssl'...
HEAD is now at c7db323 Add “bssl::” prefix to |UpRef| and |PushToStack| in fuzzer code.
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Perl: /usr/bin/perl (found version "5.20.2")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /boringssl/build
Scanning dependencies of target boringssl_gtest
[  1%] Building CXX object CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o
Linking CXX static library libboringssl_gtest.a
[  1%] Built target boringssl_gtest
[  1%] Generating crypto_test_data.cc
/usr/local/go/bin/go: 1: /usr/local/go/bin/go:ELF: not found
/usr/local/go/bin/go: 1: /usr/local/go/bin/go: Syntax error: Unterminated quoted string
CMakeFiles/crypto_test_data.dir/build.make:124: recipe for target 'crypto_test_data.cc' failed
make[2]: *** [crypto_test_data.cc] Error 2
CMakeFiles/Makefile2:128: recipe for target 'CMakeFiles/crypto_test_data.dir/all' failed
make[1]: *** [CMakeFiles/crypto_test_data.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c git clone https://boringssl.googlesource.com/boringssl &&     cd boringssl &&     git reset --hard c7db3232c397aa3feb1d474d63a1c4dd674b6349 &&     sed -i s/" -Werror"//g CMakeLists.txt &&     mkdir -p build  &&     cd build  &&     cmake -DCMAKE_CXX_FLAGS="-lrt" ..  &&     make  &&     cd ..  &&     sudo mkdir -p /opt/boringssl  &&     sudo cp -R include /opt/boringssl/  &&     sudo mkdir -p /opt/boringssl/lib  &&     sudo cp build/ssl/libssl.a /opt/boringssl/lib/  &&     sudo cp build/crypto/libcrypto.a /opt/boringssl/lib/' returned a non-zero code: 2
make: *** [Makefile:4: build] Error 2

**Comment by atyenoria** [comment]
hmm... not sure of this issue as of now. 
Can you try the other version of boring ssl from Google?
