### ISSUE TITLE
How to change the configs files: janus.plugin.streaming.jcfg?

### ISSUE THREAD

**Issue by pacorampas** [atyenoria/janus-webrtc-gateway-docker#44]
Hello I trying to change the plugins configs files but I can't.

I do the following:
1- Add this lines in Docker file
```
COPY conf/janus.plugin.streaming.jcfg /opt/janus/etc/janus/
COPY conf/janus.plugin.streaming.jcfg.sample /opt/janus/etc/janus/
```
 just before this: 
```CMD nginx && janus```

2- Then I create a new image whit: `docker build -t tag-name .``

4- Run the image: `@docker run --rm -p 80:80 -p 8088:8088 -p 8188:8188 --name="janus" -it -t tag-name`

Into the janus.plugin.streaming.jcfg I uncommented this lines:
```
h264-sample: {
	type = "rtp"
	id = 10
	description = "H.264 live stream coming from gstreamer"
	audio = false
	video = true
	videoport = 8004
	videopt = 126
	videortpmap = "H264/90000"
	videofmtp = "profile-level-id=42e01f;packetization-mode=1"
}
```

Then, I expected to have a the https://janus.conf.meetecho.com/streamingtest.html into streams lis from the streamingtest.html. I am running my own instance of streamingtest locally, here the example from janus: https://janus.conf.meetecho.com/streamingtest.html

But the h264-sample isn't there. So, what is wrong? How I be able to change the confs?

Thanks!

**Comment by atyenoria** [comment]
copying the conf file after building janus is fine?

**Comment by pacorampas** [comment]
I try to copy the files before build and same result
