### ISSUE TITLE
wss doesn't work

### ISSUE THREAD

**Issue by gharsallahmoez** [atyenoria/janus-webrtc-gateway-docker#45]
I have a public server bought it from Digitalocean, I installed docker and running these commands :
1. git clone https://github.com/atyenoria/janus-webrtc-gateway-docker.git && cd janus-webrtc-gateway-docker
2. make build
3. make run

but wss doesn't work, is there any something I missed? do I have to change something in the container? server name or something else? please let me know.

**Comment by adrien-prototype** [comment]
@gharsallahmoez did you find a solution for this ? I'd be very interested. Thanks !

**Comment by RadhikaPPatel** [comment]
@gharsallahmoez Did you find a solution for allowing wss? Please let me know I'd be very interested.
