### ISSUE TITLE
Docker Pull from Docker Hub available for this?

### ISSUE THREAD

**Issue by haneef95** [atyenoria/janus-webrtc-gateway-docker#55]
Hi,

Thanks for the detailed instructions and nice package.

Is this available to pull from docker?

My steps now:
Download -> Build -> Upload to registry -> Launch Azure Container Instance

If there was a docker pull package (from Docker Hub or another public registry), I could just:
Launch Azure Container Instance

Kind regards,

**Comment by atyenoria** [comment]
not available

**Comment by cdvv7788** [comment]
@atyenoria I can setup github actions to automatically send a docker image to docker hub when changes are made to master branch, or when a new release/tag is created. Do you want this in the repository? I can send a PR...you would only need to add your secrets for dockerhub in the repository settings once we are ready to go.

**Comment by haneef95** [comment]
Do you have a link to it @cdvv7788 ?

Thanks,
