### ISSUE TITLE
Specifying STUN/TURN servers

### ISSUE THREAD

**Issue by jasonkang14** [atyenoria/janus-webrtc-gateway-docker#60]
Your work has been great. I am using your docker container to test my app. 
As I try to test a `videroom` plugin, I realized that I need to specify STUN server in order to use the service via internet. 

How can I specify STUN servers for your container?

**Comment by atyenoria** [comment]
use google stun just for test

**Comment by jasonkang14** [comment]
do I have to set up something inside the docker container? Or is using a list of stun servers as an argument when initiating Janus sufficient?

**Comment by kuzm1ch** [comment]
@jasonkang14  A list of stun servers as an argument when initiating Janus is ok. 

You will need to configure STUN on the Janus side in case when the gateway is behind NAT. https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L220
