### ISSUE TITLE
how to get rtmp

### ISSUE THREAD

**Issue by jys923** [atyenoria/janus-webrtc-gateway-docker#67]
hello Akinori Nakajima
I run your command in docker 
"IP=0.0.0.0
PORT=8888
/root/bin/ffmpeg -y -i  "rtmp://$IP:80/rtmp_relay/$1  live=1"  -c:v libx264 -profile:v main -s 640x480  -an -preset ultrafast  -tune zerolatency -f rtp  rtp://$IP:$PORT"

root@yoon-Virtual-Machine:/opt# ffmpeg -y -i  "rtmp://$IP:80/rtmp_relay/$1  live=1"  -c:v libx264 -profile:v main -s 640x480  -an -preset ultrafast  -tune zerolatency -f rtp  rtp://$IP:$PORT
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-libxcb --enable-libpulse --enable-alsa
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtmp @ 0x55971328f6c0] Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.
[rtmp @ 0x55971328f6c0] Cannot read RTMP handshake response
rtmp://0.0.0.0:80/rtmp_relay/  live=1: End of file

I find rtmp  setting in "nginx.conf"  
I cannot find

my goal is live steaming low latency
so
OBS > RTMP > nginx > ffmpeg > janus >client
I think Similar your model

Q1.Is your docker  connect nginx-Rtmp ??

**Comment by 0xARROWK** [comment]
I agree with you, any help would be welcome ! (Thanks for ask this question)

**Comment by vegalou** [comment]
### Janus is a webrtc gateway for signaling & co-turn utility on P2P video. 

Looking for HTML5 video solution on NGINX, my experience is under 2 seconds in rtmp streaming. 

If you could feed Janus via FFMPEG then just use transcode and forwarding from source video, but Janus is not a `streaming server`.

**Comment by 0xARROWK** [comment]
Hi @vegalou can I contact you via a mail adress or something else ? I don't want to pollute @jys923 issue any more (except if he is interested).

If you don't want to share your email address here and, of course, you agree to answer my few questions, please send me a message to mathew.contactme@gmail.com

**Comment by vegalou** [comment]
Sure, You're welcome. You wrote it, already. ;-) 

vegalou`@gmail.com`
