### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by c4b4d4** [atyenoria/janus-webrtc-gateway-docker#68]
How am I supposed to configure the SSL certs in this docker? I see a BoringSSL thing, but how does it configure?

I’m running the docker in the cloud, thru my own domain.

**Comment by c4b4d4** [comment]
I managed to specify the certs thru this configuration on the nginx:

```
# HTTPS server
    #
    server {
	listen       443 ssl;
        server_name  localhost;

        ssl_certificate      /usr/local/nginx/fullcert.crt;
        ssl_certificate_key  /usr/local/nginx/key.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
```

But when I run the docker, I'm getting warnings that the HTTP/WSS are disabled:

<img width="905" alt="Screen Shot 2020-08-08 at 17 24 44" src="https://user-images.githubusercontent.com/375183/89720837-24939a00-d99c-11ea-9fe3-29c5c73645d1.png">

<img width="754" alt="Screen Shot 2020-08-08 at 17 12 49" src="https://user-images.githubusercontent.com/375183/89720692-b4d0df80-d99a-11ea-9f56-d0fdcaa449c0.png">

How am I supposed to turn it on? Also, if I just head to my **localhost:443**, I'm seeing the following website:

<img width="607" alt="Screen Shot 2020-08-08 at 17 15 32" src="https://user-images.githubusercontent.com/375183/89720707-da5de900-d99a-11ea-8fe1-4e18c2d33ec6.png">

So HTTPS certs are good, but Janus is not detecting an HTTPS/WSS configuration.

**Comment by dvision1979** [comment]
Hello @kzka90 
Did you manage to get it working? Would you share your solution?
Thank you.
