### ISSUE TITLE
WEBRTC -> RTP -> RTMP question

### ISSUE THREAD

**Issue by dvision1979** [atyenoria/janus-webrtc-gateway-docker#70]
Hi @atyenoria,

I got your docker solution up and runnin', so thank you for your hard work.
What I want to achieve and I have a hard time doing it is:
WEBRTC -> RTP -> FFMPEG

I created the SDP file:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=RTP Video
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 56.15.102
m=audio 5004 RTP/AVP 111
a=rtpmap:111 OPUS/48000/2
m=video 5002 RTP/AVP 96
a=rtpmap:96 VP8/90000

I ran the instructions in Chrome console:
var register = { "request": "rtp_forward", "publisher_id": 1697499877952907, "room": 1234, "video_port": 8050, "host": "<my receiving host", "secret" : "adminpwd" }
sfutest.send({"message": register});

then tried to get the stream in ffmpeg, but there was nothing received:
[sdp @ 0x55e23fc0e900] Could not find codec parameters for stream 1 (Video: vp8, yuv420p): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, sdp, from 'janus.sdp':
  Metadata:
    title           : RTP Video
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Stream #0:1: Video: vp8, yuv420p, 90k tbr, 90k tbn, 90k tbc

Could you please help me understand what is port 8050 (there is no such port listening from docker), where is the secret coming from (room secret?) and did I got the SDP file right?

Thank you in advance.

**Comment by dvision1979** [comment]
I managed  to find a working SDP file, now it is working.

**Comment by alg** [comment]
@danionescu2007 Can you share SDP you managed to get working with me, please?
