### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Hoang-Minh** [atyenoria/janus-webrtc-gateway-docker#72]
make build gives me this error on my windows 10
![image](https://user-images.githubusercontent.com/8659719/140826555-8ee6c859-1664-44bb-ab4d-2c827163d0b1.png)

**Comment by atyenoria** [comment]
sorry, I am not win expert

**Comment by Hoang-Minh** [comment]
Hi @atyenoria  to be exact, I'm trying to install it under Windows system for linux. As you can see in the error message, it says that connection refused, meaning that, the ftp server is unavailable.

**Comment by atyenoria** [comment]
then, please check the right url

**Comment by Hoang-Minh** [comment]
How do I check it ? I'm following your instructions on the home page.

**Comment by Meonardo** [comment]
> How do I check it ? I'm following your instructions on the home page.

Please change the `pcre-8.41.tar.gz` download URL in the [Dockerfile](https://github.com/atyenoria/janus-webrtc-gateway-docker/blob/adc21598e1adaa17e977bc6c5c0873a1d5910944/Dockerfile#L154).
I upload one `pcre-8.41.tar.gz` copy to my repo directory, you can replace the original one to [this](https://github.com/Meonardo/janus-webrtc-gateway-docker/raw/master/resources/pcre-8.41.tar.gz).

**Comment by Hoang-Minh** [comment]
@Meonardo Thank you. I will try it out

**Comment by jaapiyo** [comment]
It looks like PCRE is end-of-life and thus no longer available for download.

_The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. This version of PCRE is now at end of life, and is no longer being actively maintained. Version 8.45 is expected to be the final release of the older PCRE library, and new projects should use PCRE2 instead._ From: https://pcre.org/

I created a git just to continue my installation, it's available here: https://github.com/jaapiyo/pcre/raw/main/pcre-8.41.tar.gz

**Comment by atyenoria** [comment]
understood. I will try creating PR if possible.

**Comment by trgkyle** [comment]
> > How do I check it ? I'm following your instructions on the home page.
> 
> Please change the `pcre-8.41.tar.gz` download URL in the [Dockerfile](https://github.com/atyenoria/janus-webrtc-gateway-docker/blob/adc21598e1adaa17e977bc6c5c0873a1d5910944/Dockerfile#L154). I upload one `pcre-8.41.tar.gz` copy to my repo directory, you can replace the original one to [this](https://github.com/Meonardo/janus-webrtc-gateway-docker/raw/master/resources/pcre-8.41.tar.gz).

Yub just modify that line and replace with
`wget https://osdn.net/frs/g_redir.php?m=rwthaachen&f=pcre%2Fpcre%2F8.41%2Fpcre-8.41.tar.gz && \`
`mv g_redir.php?m=rwthaachen&f=pcre%2Fpcre%2F8.41%2Fpcre-8.41.tar.gz pcre-$PCRE.tar.gz && \`
