### ISSUE TITLE
I'm confused about installation COTURN Server and Docker Image starting. Help me Please.

### ISSUE THREAD

**Issue by chegmarco1989** [atyenoria/janus-webrtc-gateway-docker#73]
Hi All.

I'm a bit confused on two levels.

**I -** Already, when I read the README of the Docker that you advise me, I do not understand **point 4** of the installation instructions:

```
1. git clone https://github.com/atyenoria/janus-webrtc-gateway-docker.git && cd janus-webrtc-gateway-docker
2. make build
3. make run
4. star this repository after succeeding. Create the issue if you failed. We will help you as much as possible
```

**How then to start the repository as advised in point 4 above ??? If not, with which command to start it and how ???**

**II -** When I open the Dockfile, I see COTURN Server installation commands:

```
RUN COTURN="4.5.0.8" && wget https://github.com/coturn/coturn/archive/$COTURN.tar.gz && \
    tar xzvf $COTURN.tar.gz && \
    cd coturn-$COTURN && \
    ./configure && \
    make && make install
```

**So, I would like to know if I have to run these Turn installation commands myself after installing the Docker image ???**

**Or by installing the Docker image itself (https://github.com/atyenoria/janus-webrtc-gateway-docker), **COTURN Server** will install automatically ???**

Please enlighten me on these two points.

**Comment by atyenoria** [comment]
>, I would like to know if I have to run these Turn installation commands myself after installing the Docker image ???

yes, modify the startup script by yourself

**Comment by chegmarco1989** [comment]
> yes, modify the startup script by yourself

Thanks @atyenoria for the answer but I think you don't understand me apparently. What I meant, I would like to know **if I should open my Ubuntu Terminal, and run the following commands myself:**

```
RUN COTURN="4.5.0.8" && wget https://github.com/coturn/coturn/archive/$COTURN.tar.gz && \
     tar xzvf $COTURN.tar.gz && \
     cd coturn-$COTURN && \
     ./configure && \
     make && make install
```

 **???**
**Or does the Docker image take care of launching them for us and installing the COTURN Server for us ???**

**Comment by atyenoria** [comment]
already answered
