### ISSUE TITLE
continue to update 

### ISSUE THREAD

**Issue by wangsrGit119** [atyenoria/janus-webrtc-gateway-docker#76]
## Hi, friend !  I want to update .
----------------------
> the repo link [https://github.com/wangsrGit119/janus-webrtc-gateway-docker](https://github.com/wangsrGit119/janus-webrtc-gateway-docker)
----------------------
> Dockerhub address [https://hub.docker.com/r/sucwangsr/janus-webrtc-gateway-docker/tags](https://hub.docker.com/r/sucwangsr/janus-webrtc-gateway-docker/tags)

## image version

|  janus-webrtc-docker:version |  janus:version |
| ------------ | ------------ |
|  20220407 |  1.0.0 |
|  20220617 | 1.0.1   |
|  20220618 | 1.0.2   |
|  20220627 | 1.0.3   |
|  20220813 | 1.0.4   |
|  20221018 | 1.1.0   |
|  20230108 | 1.1.1   |

**Comment by atyenoria** [comment]
@wangsrGit119  oh, are your really willing to take over this repo?

**Comment by wangsrGit119** [comment]
> @wangsrGit119 oh, are your really willing to take over this repo?

>yes, but my idea is janus 0.x version use this repo, after  janus  1.0 use my repo.  the  version of  janus 0.x and 1.x gap is huge, so   i think wo can use two repo ( you can link the 1.x version to my repo and in my repo I link 0.x version to here  )
--------------------------
like :point_down:
![image](https://user-images.githubusercontent.com/32221726/211230023-d978b59d-548f-4c8e-aebd-6a04b5336269.png)

**Comment by atyenoria** [comment]
got it. I will add the link. thanks
