### ISSUE TITLE
oneway bbroadcasting demo

### ISSUE THREAD

**Issue by invisiblecoder99** [atyenoria/janus-webrtc-gateway-docker#9]
oneway bbroadcasting demo needed based on your docker

**Comment by atyenoria** [comment]
Possible, but What kinds of solution do you need? For example, Live commerce, web conference broadcast. It is necessary to know that info.

**Comment by invisiblecoder99** [comment]
one way broadcasting webrtc to rtmp code is better

**Comment by atyenoria** [comment]
I showed the example in README.md. 
Have you tried that?

**Comment by invisiblecoder99** [comment]
i need automation for multiple streams not manual

**Comment by atyenoria** [comment]
That  is beyond this repo. PR will be welcomed. Thanks.

**Comment by invisiblecoder99** [comment]
give your skype details

**Comment by HeriBrito** [comment]
Hi,

@quickstreamingmedia, i saw that you has made something with kurento (kurento-rtmp), has you found the solution using SDP on-demand with this docker-janus version?

Regards

**Comment by invisiblecoder99** [comment]
Not really I never worked with Janus
